# Generated by Django 2.2.4 on 2019-09-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20201027_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name_field',
            field=models.CharField(blank=True, db_column='name', help_text='optional', max_length=256, null=True, verbose_name='name'),
        ),
    ]
