# Generated by Django 5.2.5 on 2025-08-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_alter_article_id_alter_attachment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='enable_unsubscribe',
            field=models.BooleanField(default=True),
        ),
    ]
