# Generated by Django 5.1.1 on 2024-10-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_newsletter_subscription_generator_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='enable_unsubscribe',
            field=models.BooleanField(default=True),
        ),
    ]
