# Generated by Django 5.2.2 on 2025-08-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_article_image_thumbnail_width'),
        ('newsletter', '0010_newsletter_enable_unsubscribe'),
    ]

    operations = [
    ]
