# Generated by Django 5.2.5 on 2025-08-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_newsletter_subscription_generator_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='enable_unsubscribe',
            field=models.BooleanField(default=True),
        ),
    ]
